In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Train (2).csv')
test_given = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Test (2).csv')
sample_submission = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/SampleSubmission (2).csv')

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Applicant_ID    56000 non-null  object 
 1   form_field1     53471 non-null  float64
 2   form_field2     52156 non-null  float64
 3   form_field3     55645 non-null  float64
 4   form_field4     55645 non-null  float64
 5   form_field5     55645 non-null  float64
 6   form_field6     42640 non-null  float64
 7   form_field7     50837 non-null  float64
 8   form_field8     42640 non-null  float64
 9   form_field9     47992 non-null  float64
 10  form_field10    55645 non-null  float64
 11  form_field11    24579 non-null  float64
 12  form_field12    46105 non-null  float64
 13  form_field13    50111 non-null  float64
 14  form_field14    56000 non-null  int64  
 15  form_field15    33525 non-null  float64
 16  form_field16    42964 non-null  float64
 17  form_field17    44849 non-null 

In [4]:
null = train.isna().sum()/len(train)
null[null>0].sort_values()

form_field19    0.000071
form_field49    0.006339
form_field29    0.006339
form_field3     0.006339
form_field4     0.006339
form_field5     0.006339
form_field20    0.006339
form_field10    0.006339
form_field28    0.006339
form_field38    0.006339
form_field34    0.006339
form_field43    0.010143
form_field33    0.022429
form_field42    0.023625
form_field36    0.035625
form_field1     0.045161
form_field2     0.068643
form_field39    0.075196
form_field7     0.092196
form_field44    0.096125
form_field32    0.097321
form_field37    0.097321
form_field25    0.097321
form_field13    0.105161
form_field26    0.132821
form_field9     0.143000
form_field27    0.166054
form_field12    0.176696
form_field18    0.185750
form_field50    0.197429
form_field17    0.199125
form_field16    0.232786
form_field24    0.237446
form_field6     0.238571
form_field8     0.238571
form_field21    0.283107
form_field46    0.284000
form_field22    0.364286
form_field48    0.373018
form_field15    0.401339


In [5]:
# Encoding categorical variables
train['form_field47'].replace('charge',1, inplace=True)
train['form_field47'].replace('lending',0, inplace=True)
train['default_status'].replace('yes',1, inplace=True)
train['default_status'].replace('no',0, inplace=True)

test_given['form_field47'].replace('charge',1, inplace=True)
test_given['form_field47'].replace('lending',0, inplace=True)


In [6]:
#from sklearn.ensemble import RandomForestClassifier
#model = RandomForestClassifier()
#model.fit(X,Y)
#importance = model.feature_importances_
#for i,v in enumerate(importance):
#    print('Feature: %0d, Score: %.5f' % (i,v))

In [7]:
#plt.bar([i for i in range(len(importance))], importance)
#plt.show()

In [8]:
X = train.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39','default_status'], axis=1)
Y = train.iloc[:,-1]

test_given_new = test_given.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39'], axis=1)

In [9]:
X_null = test_given.isna().sum()/len(test_given)
X_null[X_null>0].sort_values()

form_field3     0.006083
form_field4     0.006083
form_field5     0.006083
form_field49    0.006083
form_field38    0.006125
form_field28    0.006125
form_field29    0.006125
form_field20    0.006125
form_field10    0.006125
form_field34    0.006125
form_field43    0.010417
form_field33    0.020625
form_field42    0.024083
form_field36    0.037625
form_field1     0.046250
form_field2     0.071208
form_field39    0.076208
form_field7     0.092958
form_field32    0.094000
form_field37    0.094000
form_field25    0.094000
form_field44    0.098417
form_field13    0.102625
form_field26    0.132167
form_field9     0.141667
form_field27    0.162917
form_field12    0.174292
form_field18    0.182042
form_field17    0.195625
form_field50    0.199875
form_field16    0.228083
form_field6     0.233500
form_field8     0.233500
form_field24    0.233542
form_field21    0.279458
form_field46    0.286875
form_field22    0.363500
form_field48    0.371750
form_field15    0.399667
form_field35    0.411083


In [10]:
X.replace(np.nan,-999, inplace=True)
test_given_new.replace(np.nan,-999, inplace=True)

In [11]:
#Splitting into test and train set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state = 0)

In [12]:
#X.isna().sum()

In [13]:
from catboost import CatBoostClassifier

classifier_cat = CatBoostClassifier(max_depth =1.0, iterations = 200, learning_rate = 0.5)
classifier_cat.fit(X_train, Y_train)

0:	learn: 0.5323351	total: 115ms	remaining: 22.8s
1:	learn: 0.4957681	total: 164ms	remaining: 16.2s
2:	learn: 0.4766687	total: 211ms	remaining: 13.9s
3:	learn: 0.4660769	total: 258ms	remaining: 12.7s
4:	learn: 0.4552426	total: 301ms	remaining: 11.7s
5:	learn: 0.4491829	total: 372ms	remaining: 12s
6:	learn: 0.4465277	total: 408ms	remaining: 11.3s
7:	learn: 0.4440085	total: 445ms	remaining: 10.7s
8:	learn: 0.4412585	total: 486ms	remaining: 10.3s
9:	learn: 0.4390698	total: 533ms	remaining: 10.1s
10:	learn: 0.4369579	total: 579ms	remaining: 9.94s
11:	learn: 0.4354312	total: 622ms	remaining: 9.74s
12:	learn: 0.4343165	total: 669ms	remaining: 9.62s
13:	learn: 0.4332184	total: 711ms	remaining: 9.44s
14:	learn: 0.4323274	total: 758ms	remaining: 9.35s
15:	learn: 0.4314028	total: 797ms	remaining: 9.16s
16:	learn: 0.4305312	total: 833ms	remaining: 8.96s
17:	learn: 0.4297007	total: 874ms	remaining: 8.84s
18:	learn: 0.4292827	total: 933ms	remaining: 8.89s
19:	learn: 0.4288560	total: 970ms	remaining

161:	learn: 0.4085881	total: 4.68s	remaining: 1.1s
162:	learn: 0.4085585	total: 4.7s	remaining: 1.07s
163:	learn: 0.4085246	total: 4.72s	remaining: 1.03s
164:	learn: 0.4084932	total: 4.74s	remaining: 1s
165:	learn: 0.4084593	total: 4.75s	remaining: 973ms
166:	learn: 0.4084249	total: 4.77s	remaining: 942ms
167:	learn: 0.4084032	total: 4.79s	remaining: 912ms
168:	learn: 0.4083809	total: 4.8s	remaining: 881ms
169:	learn: 0.4083513	total: 4.82s	remaining: 851ms
170:	learn: 0.4083205	total: 4.85s	remaining: 822ms
171:	learn: 0.4082771	total: 4.88s	remaining: 794ms
172:	learn: 0.4082440	total: 4.9s	remaining: 764ms
173:	learn: 0.4082149	total: 4.92s	remaining: 735ms
174:	learn: 0.4081898	total: 4.94s	remaining: 706ms
175:	learn: 0.4081647	total: 4.96s	remaining: 676ms
176:	learn: 0.4081011	total: 4.97s	remaining: 647ms
177:	learn: 0.4080702	total: 4.99s	remaining: 617ms
178:	learn: 0.4080342	total: 5.01s	remaining: 588ms
179:	learn: 0.4079900	total: 5.03s	remaining: 558ms
180:	learn: 0.40794

In [14]:
Y_pred_cat = classifier_cat.predict(X_test)
Y_pred_proba3_cat = classifier_cat.predict_proba(X_test)[:,1]
Y_pred_proba3_cat

array([0.21678569, 0.47766942, 0.30947927, ..., 0.35537702, 0.2016005 ,
       0.09970353])

In [15]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc2_cat = roc_auc_score(Y_test,Y_pred_proba3_cat)
auc2_cat

0.8319919096883488

In [16]:
Y_pred_proba_sta = classifier_cat.predict_proba(test_given_new)[:,1]
Y_pred_proba_sta

array([0.46886468, 0.26057341, 0.34181534, ..., 0.38485335, 0.56051337,
       0.18033422])

In [17]:
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_sta
sub

sub.to_csv('Comp_submission(catboost-999).csv', index=False)

In [18]:
#Using gradientboosting(best)
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

classifier_grad = GradientBoostingClassifier(n_estimators = 200)
classifier_grad.fit(X_train, Y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [22]:
Y_pred_grad = classifier_grad.predict(X_test)
Y_pred_proba_grad = classifier_grad.predict_proba(X_test)[:,1]
Y_pred_proba_grad.reshape(-1,1)

array([[0.18335501],
       [0.53308363],
       [0.37357428],
       ...,
       [0.405452  ],
       [0.18417906],
       [0.08304993]])

In [23]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_sta = roc_auc_score(Y_test,Y_pred_proba_grad)
auc_sta

0.8333435224968916

In [25]:
#Classification report
from sklearn import metrics
print('Accuracy:', metrics.accuracy_score(Y_test,Y_pred_grad))
print('Precision:', metrics.precision_score(Y_test,Y_pred_grad))
print('Recall:', metrics.recall_score(Y_test,Y_pred_grad))
print('F1:', metrics.f1_score(Y_test,Y_pred_grad))


Accuracy: 0.8101785714285714
Precision: 0.6627906976744186
Recall: 0.4410464259395726
F1: 0.529646017699115


In [26]:
# to predict using the test set given
Y_pred_proba_grad = classifier_grad.predict_proba(test_given_new)[:,1]
Y_pred_proba_grad

array([0.44616608, 0.27476173, 0.37704787, ..., 0.29726805, 0.50859224,
       0.23420865])

In [27]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_grad
sub

sub.to_csv('Comp_submission(gradboost-999).csv', index=False)