In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Train (2).csv')
test_given = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Test (2).csv')
sample_submission = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/SampleSubmission (2).csv')

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Applicant_ID    56000 non-null  object 
 1   form_field1     53471 non-null  float64
 2   form_field2     52156 non-null  float64
 3   form_field3     55645 non-null  float64
 4   form_field4     55645 non-null  float64
 5   form_field5     55645 non-null  float64
 6   form_field6     42640 non-null  float64
 7   form_field7     50837 non-null  float64
 8   form_field8     42640 non-null  float64
 9   form_field9     47992 non-null  float64
 10  form_field10    55645 non-null  float64
 11  form_field11    24579 non-null  float64
 12  form_field12    46105 non-null  float64
 13  form_field13    50111 non-null  float64
 14  form_field14    56000 non-null  int64  
 15  form_field15    33525 non-null  float64
 16  form_field16    42964 non-null  float64
 17  form_field17    44849 non-null 

In [4]:
test_given.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 51 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Applicant_ID  24000 non-null  object 
 1   form_field1   22890 non-null  float64
 2   form_field2   22291 non-null  float64
 3   form_field3   23854 non-null  float64
 4   form_field4   23854 non-null  float64
 5   form_field5   23854 non-null  float64
 6   form_field6   18396 non-null  float64
 7   form_field7   21769 non-null  float64
 8   form_field8   18396 non-null  float64
 9   form_field9   20600 non-null  float64
 10  form_field10  23853 non-null  float64
 11  form_field11  10602 non-null  float64
 12  form_field12  19817 non-null  float64
 13  form_field13  21537 non-null  float64
 14  form_field14  24000 non-null  int64  
 15  form_field15  14408 non-null  float64
 16  form_field16  18526 non-null  float64
 17  form_field17  19305 non-null  float64
 18  form_field18  19631 non-nu

In [5]:
# Encoding categorical variables
train['form_field47'].replace('charge',1, inplace=True)
train['form_field47'].replace('lending',0, inplace=True)
train['default_status'].replace('yes',1, inplace=True)
train['default_status'].replace('no',0, inplace=True)

test_given['form_field47'].replace('charge',1, inplace=True)
test_given['form_field47'].replace('lending',0, inplace=True)


In [6]:
X = train.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39','default_status'], axis=1)
Y = train.iloc[:,-1]

test_given_new = test_given.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39'], axis=1)

In [7]:
X["form_field1"].replace(np.nan, X["form_field1"].mean(), inplace=True)
X["form_field2"].replace(np.nan, X["form_field2"].mean(), inplace=True)
X["form_field3"].replace(np.nan, X["form_field3"].mean(), inplace=True)
#X["form_field4"].replace(np.nan, X["form_field4"].mean(), inplace=True)
X["form_field5"].replace(np.nan, X["form_field5"].mean(), inplace=True)
X["form_field6"].replace(np.nan, X["form_field6"].mean(), inplace=True)
X["form_field7"].replace(np.nan, X["form_field7"].mean(), inplace=True)
X["form_field8"].replace(np.nan, X["form_field8"].mean(), inplace=True)
X["form_field9"].replace(np.nan, X["form_field9"].mean(), inplace=True)
X["form_field10"].replace(np.nan, X["form_field10"].mean(), inplace=True)
X["form_field12"].replace(np.nan, X["form_field12"].mean(), inplace=True)
X["form_field13"].replace(np.nan, X["form_field13"].mean(), inplace=True)
X["form_field15"].replace(np.nan, X["form_field15"].mean(), inplace=True)
X["form_field16"].replace(np.nan, X["form_field16"].mean(), inplace=True)
#X["form_field17"].replace(np.nan, X["form_field17"].mean(), inplace=True)
#X["form_field18"].replace(np.nan, X["form_field18"].mean(), inplace=True)
X["form_field19"].replace(np.nan, X["form_field19"].mean(), inplace=True)
X["form_field20"].replace(np.nan, X["form_field20"].mean(), inplace=True)
X["form_field21"].replace(np.nan, X["form_field21"].mean(), inplace=True)
X["form_field22"].replace(np.nan, X["form_field22"].mean(), inplace=True)
X["form_field24"].replace(np.nan, X["form_field24"].mean(), inplace=True)
X["form_field25"].replace(np.nan, X["form_field25"].mean(), inplace=True)
X["form_field26"].replace(np.nan, X["form_field26"].mean(), inplace=True)
X["form_field27"].replace(np.nan, X["form_field27"].mean(), inplace=True)
X["form_field28"].replace(np.nan, X["form_field28"].mean(), inplace=True)
X["form_field29"].replace(np.nan, X["form_field29"].mean(), inplace=True)
#X["form_field30"].replace(np.nan, X["form_field30"].mean(), inplace=True)
X["form_field32"].replace(np.nan, X["form_field32"].mean(), inplace=True)
X["form_field33"].replace(np.nan, X["form_field33"].mean(), inplace=True)
X["form_field34"].replace(np.nan, X["form_field34"].mean(), inplace=True)
#X["form_field35"].replace(np.nan, X["form_field35"].mean(), inplace=True)
X["form_field36"].replace(np.nan, X["form_field36"].mean(), inplace=True)
X["form_field37"].replace(np.nan, X["form_field37"].mean(), inplace=True)
X["form_field38"].replace(np.nan, X["form_field38"].mean(), inplace=True)
#X["form_field39"].replace(np.nan, X["form_field39"].mean(), inplace=True)
X["form_field42"].replace(np.nan, X["form_field42"].mean(), inplace=True)
X["form_field43"].replace(np.nan, X["form_field43"].mean(), inplace=True)
X["form_field44"].replace(np.nan, X["form_field44"].mean(), inplace=True)
X["form_field46"].replace(np.nan, X["form_field46"].mean(), inplace=True)
X["form_field48"].replace(np.nan, X["form_field48"].mean(), inplace=True)
X["form_field49"].replace(np.nan, X["form_field49"].mean(), inplace=True)
X["form_field50"].replace(np.nan, X["form_field50"].mean(), inplace=True)

In [8]:
Y.shape

(56000,)

In [9]:
test_given_new["form_field1"].replace(np.nan, test_given_new["form_field1"].mean(), inplace=True)
test_given_new["form_field2"].replace(np.nan, test_given_new["form_field2"].mean(), inplace=True)
test_given_new["form_field3"].replace(np.nan, test_given_new["form_field3"].mean(), inplace=True)
#X["form_field4"].replace(np.nan, X["form_field4"].mean(), inplace=True)
test_given_new["form_field5"].replace(np.nan, test_given_new["form_field5"].mean(), inplace=True)
test_given_new["form_field6"].replace(np.nan, test_given_new["form_field6"].mean(), inplace=True)
test_given_new["form_field7"].replace(np.nan, test_given_new["form_field7"].mean(), inplace=True)
test_given_new["form_field8"].replace(np.nan, test_given_new["form_field8"].mean(), inplace=True)
test_given_new["form_field9"].replace(np.nan, test_given_new["form_field9"].mean(), inplace=True)
test_given_new["form_field10"].replace(np.nan, test_given_new["form_field10"].mean(), inplace=True)
test_given_new["form_field12"].replace(np.nan, test_given_new["form_field12"].mean(), inplace=True)
test_given_new["form_field13"].replace(np.nan, test_given_new["form_field13"].mean(), inplace=True)
test_given_new["form_field15"].replace(np.nan, test_given_new["form_field15"].mean(), inplace=True)
test_given_new["form_field16"].replace(np.nan, test_given_new["form_field16"].mean(), inplace=True)
#X["form_field17"].replace(np.nan, X["form_field17"].mean(), inplace=True)
#X["form_field18"].replace(np.nan, X["form_field18"].mean(), inplace=True)
test_given_new["form_field19"].replace(np.nan, test_given_new["form_field19"].mean(), inplace=True)
test_given_new["form_field20"].replace(np.nan, test_given_new["form_field20"].mean(), inplace=True)
test_given_new["form_field21"].replace(np.nan, test_given_new["form_field21"].mean(), inplace=True)
test_given_new["form_field22"].replace(np.nan, test_given_new["form_field22"].mean(), inplace=True)
test_given_new["form_field24"].replace(np.nan, test_given_new["form_field24"].mean(), inplace=True)
test_given_new["form_field25"].replace(np.nan, test_given_new["form_field25"].mean(), inplace=True)
test_given_new["form_field26"].replace(np.nan, test_given_new["form_field26"].mean(), inplace=True)
test_given_new["form_field27"].replace(np.nan, test_given_new["form_field27"].mean(), inplace=True)
test_given_new["form_field28"].replace(np.nan, test_given_new["form_field28"].mean(), inplace=True)
test_given_new["form_field29"].replace(np.nan, test_given_new["form_field29"].mean(), inplace=True)
#X["form_field30"].replace(np.nan, X["form_field30"].mean(), inplace=True)
test_given_new["form_field32"].replace(np.nan, test_given_new["form_field32"].mean(), inplace=True)
test_given_new["form_field33"].replace(np.nan, test_given_new["form_field33"].mean(), inplace=True)
test_given_new["form_field34"].replace(np.nan, test_given_new["form_field34"].mean(), inplace=True)
#X["form_field35"].replace(np.nan, X["form_field35"].mean(), inplace=True)
test_given_new["form_field36"].replace(np.nan, test_given_new["form_field36"].mean(), inplace=True)
test_given_new["form_field37"].replace(np.nan, test_given_new["form_field37"].mean(), inplace=True)
test_given_new["form_field38"].replace(np.nan, test_given_new["form_field38"].mean(), inplace=True)
#X["form_field39"].replace(np.nan, X["form_field39"].mean(), inplace=True)
test_given_new["form_field42"].replace(np.nan, test_given_new["form_field42"].mean(), inplace=True)
test_given_new["form_field43"].replace(np.nan, test_given_new["form_field43"].mean(), inplace=True)
test_given_new["form_field44"].replace(np.nan, test_given_new["form_field44"].mean(), inplace=True)
test_given_new["form_field46"].replace(np.nan, test_given_new["form_field46"].mean(), inplace=True)
test_given_new["form_field48"].replace(np.nan, test_given_new["form_field48"].mean(), inplace=True)
test_given_new["form_field49"].replace(np.nan, test_given_new["form_field49"].mean(), inplace=True)
test_given_new["form_field50"].replace(np.nan, test_given_new["form_field50"].mean(), inplace=True)

In [10]:
#Splitting into test and train set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3, random_state = 0)

In [11]:
#Using Adaboost
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

classifier_ada = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1), n_estimators = 200)
classifier_ada.fit(X_train, Y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                          

In [13]:
Y_pred_ada = classifier_ada.predict(X_test)
Y_pred_proba_ada = classifier_ada.predict_proba(X_test)[:,1]
Y_pred_proba_ada

array([0.49813094, 0.49947502, 0.49910823, ..., 0.50010644, 0.49937311,
       0.49896049])

In [14]:
#from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(Y_test, Y_pred)
#cm

In [15]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_ada = roc_auc_score(Y_test,Y_pred_proba_ada)
auc_ada

0.8255761173619687

In [16]:
#Y_pred_proba1 = classifier.predict_proba(test_given_new)[:,1]
#Y_pred_proba1

In [17]:
identifier = test_given['Applicant_ID']
#identifier

sub = pd.DataFrame(identifier, columns=['Applicant_ID'])
#sub['default_status'] = Y_pred_proba1
#sub

#sub.to_csv('Comp_submission.csv', index=False)

In [19]:
#Using gradientboosting
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

classifier_grad = GradientBoostingClassifier(n_estimators = 200)
classifier_grad.fit(X_train, Y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [20]:
Y_pred_grad = classifier_grad.predict(X_test)
Y_pred_proba_grad = classifier_grad.predict_proba(X_test)[:,1]
Y_pred_proba_grad

array([0.13091588, 0.4629386 , 0.33162861, ..., 0.55547163, 0.28692166,
       0.24293952])

In [21]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_grad = roc_auc_score(Y_test,Y_pred_proba_grad)
auc_grad

0.8323611088371523

In [22]:
Y_pred_proba2_grad = classifier_grad.predict_proba(test_given_new)[:,1]
Y_pred_proba2_grad

array([0.4968716 , 0.322986  , 0.2679334 , ..., 0.25852925, 0.49109466,
       0.19316128])

In [23]:
identifier = test_given['Applicant_ID']
#identifier

#sub = pd.DataFrame(identifier, columns=['Applicant_ID'])
#sub['default_status'] = Y_pred_proba2
#sub

#sub.to_csv('Comp_submission1.csv', index=False)

In [24]:
#Using randomforest
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

classifier_rand = RandomForestClassifier(n_estimators = 200)
classifier_rand.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [26]:
Y_pred_rand = classifier_rand.predict(X_test)
Y_pred_proba_rand = classifier_rand.predict_proba(X_test)[:,1]
Y_pred_proba_rand

array([0.31 , 0.425, 0.46 , ..., 0.52 , 0.295, 0.29 ])

In [27]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_rand = roc_auc_score(Y_test,Y_pred_proba_rand)
auc_rand

0.8278128197241073

In [ ]:
from catboost import CatBoostClassifier

classifier_cat = CatBoostClassifier(max_depth =1.0, iterations = 400, learning_rate = 0.5)
classifier_cat.fit(X_train, Y_train)

In [ ]:
Y_pred_cat = classifier_cat.predict(X_test)
Y_pred_proba3_cat = classifier_cat.predict_proba(X_test)[:,1]
Y_pred_proba3_cat

In [ ]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc2_cat = roc_auc_score(Y_test,Y_pred_proba3_cat)
auc2_cat

In [ ]:
#Stacking Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

estimators = [
    ('classifier_rand', RandomForestClassifier()),
    ('classifier_cat', CatBoostClassifier()),
    ('classifier_grad', GradientBoostingClassifier)
]


sta = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

clf.fit(X_train, Y_train)

In [ ]:
Y_pred_sta = clf.predict(X_test)
Y_pred_proba_sta = clf.predict_proba(X_test)[:,1]
Y_pred_proba_sta

In [ ]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_sta = roc_auc_score(Y_test,Y_pred_proba_sta)
auc_sta

In [ ]:
Y_pred_proba_sta = classifier_grad.predict_proba(test_given_new)[:,1]
Y_pred_proba_sta

In [ ]:
identifier = test_given['Applicant_ID']
#identifier

sub = pd.DataFrame(identifier, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_sta
sub

sub.to_csv('Comp_submission2.csv', index=False)