In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Train (2).csv')
test_given = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/Test (2).csv')
sample_submission = pd.read_csv('C:/Users/USER/Desktop/DSN Hackathon/Bootcamp Qualification/SampleSubmission (2).csv')

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56000 entries, 0 to 55999
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Applicant_ID    56000 non-null  object 
 1   form_field1     53471 non-null  float64
 2   form_field2     52156 non-null  float64
 3   form_field3     55645 non-null  float64
 4   form_field4     55645 non-null  float64
 5   form_field5     55645 non-null  float64
 6   form_field6     42640 non-null  float64
 7   form_field7     50837 non-null  float64
 8   form_field8     42640 non-null  float64
 9   form_field9     47992 non-null  float64
 10  form_field10    55645 non-null  float64
 11  form_field11    24579 non-null  float64
 12  form_field12    46105 non-null  float64
 13  form_field13    50111 non-null  float64
 14  form_field14    56000 non-null  int64  
 15  form_field15    33525 non-null  float64
 16  form_field16    42964 non-null  float64
 17  form_field17    44849 non-null 

In [5]:
null = train.isna().sum()/len(train)
null[null>0].sort_values()

form_field19    0.000071
form_field49    0.006339
form_field29    0.006339
form_field3     0.006339
form_field4     0.006339
form_field5     0.006339
form_field20    0.006339
form_field10    0.006339
form_field28    0.006339
form_field38    0.006339
form_field34    0.006339
form_field43    0.010143
form_field33    0.022429
form_field42    0.023625
form_field36    0.035625
form_field1     0.045161
form_field2     0.068643
form_field39    0.075196
form_field7     0.092196
form_field44    0.096125
form_field32    0.097321
form_field37    0.097321
form_field25    0.097321
form_field13    0.105161
form_field26    0.132821
form_field9     0.143000
form_field27    0.166054
form_field12    0.176696
form_field18    0.185750
form_field50    0.197429
form_field17    0.199125
form_field16    0.232786
form_field24    0.237446
form_field6     0.238571
form_field8     0.238571
form_field21    0.283107
form_field46    0.284000
form_field22    0.364286
form_field48    0.373018
form_field15    0.401339


In [6]:
# Encoding categorical variables
train['form_field47'].replace('charge',1, inplace=True)
train['form_field47'].replace('lending',0, inplace=True)
train['default_status'].replace('yes',1, inplace=True)
train['default_status'].replace('no',0, inplace=True)

test_given['form_field47'].replace('charge',1, inplace=True)
test_given['form_field47'].replace('lending',0, inplace=True)


In [7]:
#from sklearn.ensemble import RandomForestClassifier
#model = RandomForestClassifier()
#model.fit(X,Y)
#importance = model.feature_importances_
#for i,v in enumerate(importance):
#    print('Feature: %0d, Score: %.5f' % (i,v))

In [8]:
#plt.bar([i for i in range(len(importance))], importance)
#plt.show()

In [9]:
X = train.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39','default_status'], axis=1)
Y = train.iloc[:,-1]

test_given_new = test_given.drop(['Applicant_ID','form_field23','form_field45','form_field11','form_field41','form_field40', 'form_field4','form_field17','form_field18','form_field30','form_field31','form_field35','form_field39'], axis=1)

In [10]:
X_null = test_given.isna().sum()/len(test_given)
X_null[X_null>0].sort_values()

form_field3     0.006083
form_field4     0.006083
form_field5     0.006083
form_field49    0.006083
form_field38    0.006125
form_field28    0.006125
form_field29    0.006125
form_field20    0.006125
form_field10    0.006125
form_field34    0.006125
form_field43    0.010417
form_field33    0.020625
form_field42    0.024083
form_field36    0.037625
form_field1     0.046250
form_field2     0.071208
form_field39    0.076208
form_field7     0.092958
form_field32    0.094000
form_field37    0.094000
form_field25    0.094000
form_field44    0.098417
form_field13    0.102625
form_field26    0.132167
form_field9     0.141667
form_field27    0.162917
form_field12    0.174292
form_field18    0.182042
form_field17    0.195625
form_field50    0.199875
form_field16    0.228083
form_field6     0.233500
form_field8     0.233500
form_field24    0.233542
form_field21    0.279458
form_field46    0.286875
form_field22    0.363500
form_field48    0.371750
form_field15    0.399667
form_field35    0.411083


In [11]:
X.replace(np.nan,-999, inplace=True)
test_given_new.replace(np.nan,-999, inplace=True)

In [12]:
#Splitting into test and train set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state = 0)

In [13]:
X.isna().sum()

form_field1     0
form_field2     0
form_field3     0
form_field5     0
form_field6     0
form_field7     0
form_field8     0
form_field9     0
form_field10    0
form_field12    0
form_field13    0
form_field14    0
form_field15    0
form_field16    0
form_field19    0
form_field20    0
form_field21    0
form_field22    0
form_field24    0
form_field25    0
form_field26    0
form_field27    0
form_field28    0
form_field29    0
form_field32    0
form_field33    0
form_field34    0
form_field36    0
form_field37    0
form_field38    0
form_field42    0
form_field43    0
form_field44    0
form_field46    0
form_field47    0
form_field48    0
form_field49    0
form_field50    0
dtype: int64

In [14]:
from catboost import CatBoostClassifier

classifier_cat = CatBoostClassifier(max_depth =1.0, iterations = 200, learning_rate = 0.5)
classifier_cat.fit(X_train, Y_train)

0:	learn: 0.5323351	total: 103ms	remaining: 20.5s
1:	learn: 0.4957681	total: 144ms	remaining: 14.3s
2:	learn: 0.4766687	total: 186ms	remaining: 12.2s
3:	learn: 0.4660769	total: 227ms	remaining: 11.1s
4:	learn: 0.4552426	total: 267ms	remaining: 10.4s
5:	learn: 0.4491829	total: 308ms	remaining: 9.95s
6:	learn: 0.4465277	total: 353ms	remaining: 9.73s
7:	learn: 0.4440085	total: 389ms	remaining: 9.34s
8:	learn: 0.4412585	total: 433ms	remaining: 9.19s
9:	learn: 0.4390698	total: 482ms	remaining: 9.15s
10:	learn: 0.4369579	total: 591ms	remaining: 10.1s
11:	learn: 0.4354312	total: 651ms	remaining: 10.2s
12:	learn: 0.4343165	total: 687ms	remaining: 9.88s
13:	learn: 0.4332184	total: 728ms	remaining: 9.67s
14:	learn: 0.4323274	total: 765ms	remaining: 9.44s
15:	learn: 0.4314028	total: 807ms	remaining: 9.28s
16:	learn: 0.4305312	total: 851ms	remaining: 9.16s
17:	learn: 0.4297007	total: 899ms	remaining: 9.09s
18:	learn: 0.4292827	total: 941ms	remaining: 8.96s
19:	learn: 0.4288560	total: 976ms	remaini

161:	learn: 0.4085881	total: 4.96s	remaining: 1.16s
162:	learn: 0.4085585	total: 4.98s	remaining: 1.13s
163:	learn: 0.4085246	total: 5s	remaining: 1.1s
164:	learn: 0.4084932	total: 5.02s	remaining: 1.06s
165:	learn: 0.4084593	total: 5.04s	remaining: 1.03s
166:	learn: 0.4084249	total: 5.06s	remaining: 1000ms
167:	learn: 0.4084032	total: 5.08s	remaining: 967ms
168:	learn: 0.4083809	total: 5.09s	remaining: 935ms
169:	learn: 0.4083513	total: 5.11s	remaining: 902ms
170:	learn: 0.4083205	total: 5.13s	remaining: 870ms
171:	learn: 0.4082771	total: 5.15s	remaining: 838ms
172:	learn: 0.4082440	total: 5.17s	remaining: 807ms
173:	learn: 0.4082149	total: 5.19s	remaining: 775ms
174:	learn: 0.4081898	total: 5.21s	remaining: 744ms
175:	learn: 0.4081647	total: 5.22s	remaining: 712ms
176:	learn: 0.4081011	total: 5.24s	remaining: 681ms
177:	learn: 0.4080702	total: 5.26s	remaining: 650ms
178:	learn: 0.4080342	total: 5.28s	remaining: 620ms
179:	learn: 0.4079900	total: 5.31s	remaining: 590ms
180:	learn: 0.4

In [15]:
Y_pred_cat = classifier_cat.predict(X_test)
Y_pred_proba3_cat = classifier_cat.predict_proba(X_test)[:,1]
Y_pred_proba3_cat

array([0.21678569, 0.47766942, 0.30947927, ..., 0.35537702, 0.2016005 ,
       0.09970353])

In [15]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc2_cat = roc_auc_score(Y_test,Y_pred_proba3_cat)
auc2_cat

0.8319919096883488

In [16]:
Y_pred_proba_sta = classifier_cat.predict_proba(test_given_new)[:,1]
Y_pred_proba_sta

array([0.46886468, 0.26057341, 0.34181534, ..., 0.38485335, 0.56051337,
       0.18033422])

In [17]:
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_sta
sub

sub.to_csv('Comp_submission(catboost-999).csv', index=False)

In [18]:
#Using gradientboosting(best)
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix

classifier_grad = GradientBoostingClassifier(n_estimators = 200)
classifier_grad.fit(X_train, Y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [19]:
Y_pred_grad = classifier_grad.predict(X_test)
Y_pred_proba_grad = classifier_grad.predict_proba(X_test)[:,1]
Y_pred_proba_grad.reshape(-1,1)

array([[0.18335501],
       [0.53308363],
       [0.37357428],
       ...,
       [0.405452  ],
       [0.18417906],
       [0.08304993]])

In [20]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc_sta = roc_auc_score(Y_test,Y_pred_proba_grad)
auc_sta

0.8332691444975651

In [21]:
#Classification report
from sklearn import metrics
print('Accuracy:', metrics.accuracy_score(Y_test,Y_pred_grad))
print('Precision:', metrics.precision_score(Y_test,Y_pred_grad))
print('Recall:', metrics.recall_score(Y_test,Y_pred_grad))
print('F1:', metrics.f1_score(Y_test,Y_pred_grad))


Accuracy: 0.81
Precision: 0.6622369878183831
Recall: 0.4406779661016949
F1: 0.5292035398230088


In [22]:
# to predict using the test set given
Y_pred_proba_grad = classifier_grad.predict_proba(test_given_new)[:,1]
Y_pred_proba_grad

array([0.44616608, 0.27476173, 0.37704787, ..., 0.29726805, 0.50859224,
       0.23420865])

In [23]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_grad
sub

sub.to_csv('Comp_submission(gradboost-999).csv', index=False)

In [27]:
import xgboost as xgb
xlf = xgb.XGBClassifier(objective='binary:logistic', seed=1279)
xlf.fit(X_train, Y_train)
preds = xlf.predict(X_test)

In [28]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(Y_test,preds)
auc

0.6846812236235988

In [29]:
from sklearn import metrics
print('Accuracy:', metrics.accuracy_score(Y_test,preds))

Accuracy: 0.8032142857142858


In [30]:
# to predict using the test set given
pred_proba = xlf.predict_proba(test_given_new)[:,1]
pred_proba

array([0.29783252, 0.44257453, 0.47369683, ..., 0.18358493, 0.4283754 ,
       0.2705158 ], dtype=float32)

In [31]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = Y_pred_proba_grad
sub

sub.to_csv('Comp_submission(xgbboost-999).csv', index=False)

In [33]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=2) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = CatBoostClassifier(n_estimators=300,eval_metric='Accuracy',learning_rate=0.1, random_seed= 1234, use_best_model=True )
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=300,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

0:	learn: 0.7831071	test: 0.7831071	test1: 0.7794286	best: 0.7794286 (0)	total: 143ms	remaining: 42.8s
100:	learn: 0.8233929	test: 0.8233929	test1: 0.8063214	best: 0.8066071 (85)	total: 5.26s	remaining: 10.4s
200:	learn: 0.8427500	test: 0.8427500	test1: 0.8063929	best: 0.8075357 (169)	total: 8.75s	remaining: 4.31s
299:	learn: 0.8610357	test: 0.8610357	test1: 0.8057500	best: 0.8075357 (169)	total: 12.2s	remaining: 0us

bestTest = 0.8075357143
bestIteration = 169

Shrink model to first 170 iterations.
0:	learn: 0.7801071	test: 0.7801071	test1: 0.7807857	best: 0.7807857 (0)	total: 79.7ms	remaining: 23.8s
100:	learn: 0.8236071	test: 0.8236071	test1: 0.8061429	best: 0.8065357 (84)	total: 4.89s	remaining: 9.64s
200:	learn: 0.8431429	test: 0.8431429	test1: 0.8053214	best: 0.8068571 (113)	total: 8.42s	remaining: 4.15s
299:	learn: 0.8590357	test: 0.8590357	test1: 0.8048929	best: 0.8068571 (113)	total: 11.9s	remaining: 0us

bestTest = 0.8068571429
bestIteration = 113

Shrink model to first 114 i

In [36]:
# to predict using the test set given
pred_proba = model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.31763808, 0.32717523, 0.37221894, ..., 0.3741284 , 0.50564373,
       0.17567582])

In [37]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(catboost-999stra).csv', index=False)

In [44]:
#Best
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=10) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = CatBoostClassifier(n_estimators=300,eval_metric='Accuracy',learning_rate=0.1, random_seed= 1234, use_best_model=True )
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=300,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

0:	learn: 0.7848611	test: 0.7848611	test1: 0.7792857	best: 0.7792857 (0)	total: 53.1ms	remaining: 15.9s
100:	learn: 0.8174008	test: 0.8174008	test1: 0.8067857	best: 0.8067857 (100)	total: 5.08s	remaining: 10s
200:	learn: 0.8300794	test: 0.8300794	test1: 0.8092857	best: 0.8094643 (196)	total: 10.1s	remaining: 4.95s
299:	learn: 0.8408730	test: 0.8408730	test1: 0.8110714	best: 0.8112500 (296)	total: 15.2s	remaining: 0us

bestTest = 0.81125
bestIteration = 296

Shrink model to first 297 iterations.
0:	learn: 0.7760913	test: 0.7760913	test1: 0.7801786	best: 0.7801786 (0)	total: 105ms	remaining: 31.4s
100:	learn: 0.8173214	test: 0.8173214	test1: 0.8100000	best: 0.8100000 (100)	total: 5.76s	remaining: 11.4s
200:	learn: 0.8291667	test: 0.8291667	test1: 0.8126786	best: 0.8139286 (175)	total: 10.6s	remaining: 5.21s
299:	learn: 0.8398214	test: 0.8398214	test1: 0.8132143	best: 0.8150000 (252)	total: 15.4s	remaining: 0us

bestTest = 0.815
bestIteration = 252

Shrink model to first 253 iterations.
0

In [45]:
# to predict using the test set given
pred_proba = model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.35526294, 0.19042131, 0.37280116, ..., 0.28312026, 0.56403234,
       0.23287128])

In [46]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(catboost-999stra10).csv', index=False)

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from numpy import random
#from scipy.stats import uniform as sp_randFloat
#from scipy.stats import randint as sp_randInt

#parameters = {'depth':random.rand(4,10), 'learning_rate':[0.01,0.015,0.05,0.1], 'iterations':random.rand[50,300]}

print(random.randint(4,10))

In [ ]:
#Using randomforest
#from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier

#classifier_rand = RandomForestClassifier(n_estimators = 200)
#from sklearn.model_selection import KFold,StratifiedKFold

#fold=StratifiedKFold(n_splits=10) #5 # 10 
#i=1
#for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
 #   X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  # classifier_rand = RandomForestClassifier(n_estimators = 200)
   # classifier_rand.fit(X_train,Y_train)
    #preds = classifier_rand.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    #p2 = model.predict(test_given_new)

In [56]:
# to predict using the test set given
pred_proba =  classifier_rand.predict_proba(test_given_new)[:,1]
pred_proba

array([0.375, 0.325, 0.325, ..., 0.365, 0.565, 0.17 ])

In [57]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(random-999stra10).csv', index=False)

In [61]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=10) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = CatBoostClassifier(n_estimators=2500,eval_metric='Accuracy',learning_rate=0.01, random_seed= 1234, use_best_model=True )
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=300,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

0:	learn: 0.7848611	test: 0.7848611	test1: 0.7792857	best: 0.7792857 (0)	total: 70.9ms	remaining: 2m 57s
100:	learn: 0.8001786	test: 0.8001786	test1: 0.7967857	best: 0.7975000 (66)	total: 5.11s	remaining: 2m 1s
200:	learn: 0.8046825	test: 0.8046825	test1: 0.8025000	best: 0.8025000 (199)	total: 10s	remaining: 1m 54s
300:	learn: 0.8077183	test: 0.8077183	test1: 0.8035714	best: 0.8041071 (288)	total: 14.9s	remaining: 1m 48s
400:	learn: 0.8096627	test: 0.8096627	test1: 0.8051786	best: 0.8051786 (400)	total: 19.7s	remaining: 1m 42s
500:	learn: 0.8117460	test: 0.8117460	test1: 0.8060714	best: 0.8066071 (496)	total: 24.5s	remaining: 1m 37s
600:	learn: 0.8137897	test: 0.8137897	test1: 0.8071429	best: 0.8071429 (599)	total: 29.2s	remaining: 1m 32s
700:	learn: 0.8150595	test: 0.8150595	test1: 0.8058929	best: 0.8073214 (603)	total: 34.1s	remaining: 1m 27s
800:	learn: 0.8161706	test: 0.8161706	test1: 0.8055357	best: 0.8073214 (603)	total: 38.9s	remaining: 1m 22s
900:	learn: 0.8172619	test: 0.81726

Stopped by overfitting detector  (300 iterations wait)

bestTest = 0.8121428571
bestIteration = 1172

Shrink model to first 1173 iterations.
0:	learn: 0.7762698	test: 0.7762698	test1: 0.7787500	best: 0.7787500 (0)	total: 120ms	remaining: 5m
100:	learn: 0.8000992	test: 0.8000992	test1: 0.7985714	best: 0.7992857 (90)	total: 6.38s	remaining: 2m 31s
200:	learn: 0.8048611	test: 0.8048611	test1: 0.8001786	best: 0.8005357 (130)	total: 11.3s	remaining: 2m 9s
300:	learn: 0.8082738	test: 0.8082738	test1: 0.8000000	best: 0.8012500 (233)	total: 16.4s	remaining: 1m 59s
400:	learn: 0.8098611	test: 0.8098611	test1: 0.8025000	best: 0.8025000 (399)	total: 22s	remaining: 1m 55s
500:	learn: 0.8115079	test: 0.8115079	test1: 0.8025000	best: 0.8030357 (469)	total: 26.9s	remaining: 1m 47s
600:	learn: 0.8140278	test: 0.8140278	test1: 0.8037500	best: 0.8044643 (559)	total: 31.9s	remaining: 1m 40s
700:	learn: 0.8152381	test: 0.8152381	test1: 0.8044643	best: 0.8048214 (699)	total: 36.9s	remaining: 1m 34s
800:	le

In [ ]:
# to predict using the test set given
pred_proba =  model.predict_proba(test_given_new)[:,1]
pred_proba

In [63]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Submission_tuned2(catboost-999stra10).csv', index=False)

In [16]:
import lightgbm

In [10]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=10) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = lightgbm.LGBMClassifier(n_estimators=2500,objective = 'binary',reg_alpha=26.4310,subsample = 0.99868,nthread=12,max_bin=8850,colsample_bytree=0.802, random_seed= 1234)
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=300,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 300 rounds
[100]	training's binary_logloss: 0.385116	valid_1's binary_logloss: 0.414205
[200]	training's binary_logloss: 0.370627	valid_1's binary_logloss: 0.412174
[300]	training's binary_logloss: 0.36577	valid_1's binary_logloss: 0.41192
[400]	training's binary_logloss: 0.36577	valid_1's binary_logloss: 0.41192
[500]	training's binary_logloss: 0.36577	valid_1's binary_logloss: 0.41192
Early stopping, best iteration is:
[249]	training's binary_logloss: 0.365875	valid_1's binary_logloss: 0.411898
[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 300 rounds
[100]	training's binary_logloss: 0.386314	valid_1's binary_logloss: 0.40202
[200]	training's binary_logloss: 0.371488	valid_1's binary_logloss: 0.40114
[300]

In [11]:
# to predict using the test set given
pred_proba =  model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.29341782, 0.23936078, 0.42367227, ..., 0.1946554 , 0.40145826,
       0.21455085])

In [12]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(light-999stra10).csv', index=False)

In [13]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=5) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = lightgbm.LGBMClassifier(n_estimators=2500,objective = 'binary',reg_alpha=26.4310,subsample = 0.99868,nthread=12,max_bin=8850,colsample_bytree=0.802, random_seed= 1234)
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=200,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 200 rounds
[100]	training's binary_logloss: 0.384944	valid_1's binary_logloss: 0.40931
[200]	training's binary_logloss: 0.369626	valid_1's binary_logloss: 0.407785
[300]	training's binary_logloss: 0.365656	valid_1's binary_logloss: 0.40773
[400]	training's binary_logloss: 0.365656	valid_1's binary_logloss: 0.40773
Early stopping, best iteration is:
[231]	training's binary_logloss: 0.366633	valid_1's binary_logloss: 0.407594
[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 200 rounds
[100]	training's binary_logloss: 0.383293	valid_1's binary_logloss: 0.412235
[200]	training's binary_logloss: 0.367371	valid_1's binary_logloss: 0.412057
[300]	training's binary_logloss: 0.362878	valid_1's binary_logloss: 0.412281


In [14]:
# to predict using the test set given
pred_proba =  model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.2856026 , 0.33003032, 0.3760863 , ..., 0.23686489, 0.42662034,
       0.23422481])

In [15]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(light-999stra5).csv', index=False)

In [16]:
from sklearn.model_selection import KFold,StratifiedKFold
import lightgbm as lgb

In [29]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=10) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = CatBoostClassifier(n_estimators=300,depth=6,thread_count=12,eval_metric='Accuracy',learning_rate=0.015, random_seed= 1234, use_best_model=True )
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=300,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

0:	learn: 0.7848611	test: 0.7848611	test1: 0.7792857	best: 0.7792857 (0)	total: 261ms	remaining: 1m 17s
100:	learn: 0.8021825	test: 0.8021825	test1: 0.8008929	best: 0.8008929 (100)	total: 9.17s	remaining: 18.1s
200:	learn: 0.8076984	test: 0.8076984	test1: 0.8044643	best: 0.8044643 (200)	total: 17.1s	remaining: 8.43s
299:	learn: 0.8105754	test: 0.8105754	test1: 0.8042857	best: 0.8058929 (224)	total: 24.7s	remaining: 0us

bestTest = 0.8058928571
bestIteration = 224

Shrink model to first 225 iterations.
0:	learn: 0.7760913	test: 0.7760913	test1: 0.7801786	best: 0.7801786 (0)	total: 142ms	remaining: 42.4s
100:	learn: 0.8029563	test: 0.8029563	test1: 0.8025000	best: 0.8025000 (100)	total: 9.08s	remaining: 17.9s
200:	learn: 0.8074008	test: 0.8074008	test1: 0.8057143	best: 0.8058929 (183)	total: 16.9s	remaining: 8.3s
299:	learn: 0.8103770	test: 0.8103770	test1: 0.8050000	best: 0.8060714 (236)	total: 24.5s	remaining: 0us

bestTest = 0.8060714286
bestIteration = 236

Shrink model to first 237 

In [30]:
# to predict using the test set given
pred_proba =  model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.43294136, 0.37671161, 0.37242111, ..., 0.40370345, 0.52169404,
       0.23212729])

In [31]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Submission_tuned3(catboost-999stra10).csv', index=False)

In [ ]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
from xgboost.sklearn import XGBClassifier

xgb = XGBClassifier()
gbrt = GradientBoostingClassifier()
learning_rate = [0.01,0.1,1,10,100]
n_estimators = [500,600,700,800]
max_depth = [6,8,10]

param_grid = dict(learning_rate=learning_rate, n_estimators=n_estimators, max_depth=max_depth)
                  

grid = GridSearchCV(estimator = xgb, param_grid=param_grid,scoring='recall', verbose=1, n_jobs=-1 )

grid_result = grid.fit(X_train,Y_train)
print('Best Score:', grid_result.best_score_)
print('Best_Params:', grid_result.best_params_)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.


In [17]:
from sklearn.model_selection import KFold,StratifiedKFold
from catboost import CatBoostClassifier

fold=StratifiedKFold(n_splits=15) #5 # 10 
i=1
for train_index, test_index in fold.split(X,Y):
    
    #The usual cross validation
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model  = lightgbm.LGBMClassifier(n_estimators=4000,learning_rate = 0.01,objective = 'binary',reg_alpha=26.4310,
                                     subsample = 0.99868,nthread=12,max_bin=8850,colsample_bytree=0.802, random_seed= 1234)
    
    model.fit(X_train,Y_train,eval_set=[(X_train,Y_train),(X_test, Y_test)], early_stopping_rounds=200,verbose=100,)#erly100
    preds = model.predict(X_test)
    
    #Simultaneosly Predicting on test set for submission
    p2 = model.predict(test_given_new)

[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 200 rounds
[100]	training's binary_logloss: 0.450987	valid_1's binary_logloss: 0.462867
[200]	training's binary_logloss: 0.420561	valid_1's binary_logloss: 0.436775
[300]	training's binary_logloss: 0.408148	valid_1's binary_logloss: 0.427439
[400]	training's binary_logloss: 0.401773	valid_1's binary_logloss: 0.423496
[500]	training's binary_logloss: 0.397557	valid_1's binary_logloss: 0.421121
[600]	training's binary_logloss: 0.394262	valid_1's binary_logloss: 0.419585
[700]	training's binary_logloss: 0.391458	valid_1's binary_logloss: 0.418416
[800]	training's binary_logloss: 0.38908	valid_1's binary_logloss: 0.417577
[900]	training's binary_logloss: 0.386938	valid_1's binary_logloss: 0.417024
[1000]	training's binary_logloss: 0.385	valid_1's binary_logloss: 0.416585
[1100]	training's binary_logloss: 0.383216	valid_1's bina

[2500]	training's binary_logloss: 0.366598	valid_1's binary_logloss: 0.399671
Early stopping, best iteration is:
[2316]	training's binary_logloss: 0.368489	valid_1's binary_logloss: 0.39952
[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 200 rounds
[100]	training's binary_logloss: 0.45032	valid_1's binary_logloss: 0.464185
[200]	training's binary_logloss: 0.419628	valid_1's binary_logloss: 0.442391
[300]	training's binary_logloss: 0.407239	valid_1's binary_logloss: 0.435549
[400]	training's binary_logloss: 0.400768	valid_1's binary_logloss: 0.432723
[500]	training's binary_logloss: 0.39646	valid_1's binary_logloss: 0.431395
[600]	training's binary_logloss: 0.393156	valid_1's binary_logloss: 0.430302
[700]	training's binary_logloss: 0.390379	valid_1's binary_logloss: 0.42945
[800]	training's binary_logloss: 0.388	valid_1's binary_logloss: 0.428716
[900]	training's binary_

[1400]	training's binary_logloss: 0.379147	valid_1's binary_logloss: 0.407136
[1500]	training's binary_logloss: 0.37774	valid_1's binary_logloss: 0.407034
[1600]	training's binary_logloss: 0.376363	valid_1's binary_logloss: 0.407007
[1700]	training's binary_logloss: 0.375048	valid_1's binary_logloss: 0.406942
[1800]	training's binary_logloss: 0.373754	valid_1's binary_logloss: 0.406869
[1900]	training's binary_logloss: 0.372512	valid_1's binary_logloss: 0.406784
[2000]	training's binary_logloss: 0.371285	valid_1's binary_logloss: 0.406853
Early stopping, best iteration is:
[1841]	training's binary_logloss: 0.373229	valid_1's binary_logloss: 0.406781
[LightGBM] [Warning] num_threads is set with n_jobs=-1, nthread=12 will be ignored. Current value: num_threads=-1
Training until validation scores don't improve for 200 rounds
[100]	training's binary_logloss: 0.450715	valid_1's binary_logloss: 0.461822
[200]	training's binary_logloss: 0.419964	valid_1's binary_logloss: 0.438884
[300]	traini

[500]	training's binary_logloss: 0.397367	valid_1's binary_logloss: 0.418219
[600]	training's binary_logloss: 0.394015	valid_1's binary_logloss: 0.41722
[700]	training's binary_logloss: 0.391259	valid_1's binary_logloss: 0.416477
[800]	training's binary_logloss: 0.38887	valid_1's binary_logloss: 0.416064
[900]	training's binary_logloss: 0.386762	valid_1's binary_logloss: 0.415777
[1000]	training's binary_logloss: 0.384887	valid_1's binary_logloss: 0.415625
[1100]	training's binary_logloss: 0.383133	valid_1's binary_logloss: 0.415432
[1200]	training's binary_logloss: 0.381526	valid_1's binary_logloss: 0.415497
[1300]	training's binary_logloss: 0.379987	valid_1's binary_logloss: 0.415418
[1400]	training's binary_logloss: 0.378544	valid_1's binary_logloss: 0.415328
[1500]	training's binary_logloss: 0.377116	valid_1's binary_logloss: 0.41533
[1600]	training's binary_logloss: 0.375759	valid_1's binary_logloss: 0.415375
Early stopping, best iteration is:
[1491]	training's binary_logloss: 0.3

In [18]:
# to predict using the test set given
pred_proba =  model.predict_proba(test_given_new)[:,1]
pred_proba

array([0.31921028, 0.27472736, 0.40920402, ..., 0.24005809, 0.38977581,
       0.21779062])

In [20]:
#file for submission
id = test_given['Applicant_ID']
#id

sub = pd.DataFrame(id, columns=['Applicant_ID'])
sub['default_status'] = pred_proba
sub

sub.to_csv('Comp_submission(light-999stra15).csv', index=False)

In [ ]:
# GridSearchCV
#from sklearn.model_selection import GridSearchCV
#from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier,GradientBoostingClassifier
#from xgboost.sklearn import XGBClassifier

#xgb = XGBClassifier()
#gbrt = GradientBoostingClassifier()
#learning_rate = [0.01,0.1]
#n_estimators = [500,600,700]
#max_depth = [6,8,10]

#param_grid = dict(learning_rate=learning_rate, n_estimators=n_estimators, max_depth=max_depth)
                  

#grid = GridSearchCV(estimator = xgb, param_grid=param_grid,scoring='recall', verbose=1, n_jobs=-1 )

#grid_result = grid.fit(X_train,Y_train)
#print('Best Score:', grid_result.best_score_)
#print('Best_Params:', grid_result.best_params_)